[project]
name = "Chi2_analysis_for_HideSeek_data"
version = "1.0"
authors = [
  { name="Nicolli Soares P.", email="nicolli@usp.br" },
]
description = "This library provides a parallel framework for performing chi-square and RMSE analysis between observed and expected Time-Ordered Data (TOD) from the HIDE & SEEK data. It is designed to handle large datasets efficiently using MPI for parallelism, numpy memmaps for temporary storage, and produces waterfall plots (2D colour maps) as visual output. Results are finally consolidated into a single compressed HDF5 file."
readme = "/Chi2_library/README.md"
requires-python = ">=3.8.2"

license = {text = "GNU General Public License v3.0"}
license-files = ["LICEN[CS]E*"]

# [project.urls]
# Homepage = "https://github.com/pypa/sampleproject"
# Issues = "https://github.com/pypa/sampleproject/issues"